package com.app.githubuserrepo.model

data class ProfileResponse(
    val avatar_url: String?,
    val bio: String?,
    val blog: String?,
    val company: String?,
    val created_at: String?,
    val email: String?,
    val events_url: String?,
    val followers: String?,
    val followers_url: String?,
    val following: String?,
    val following_url: String?,
    val gists_url: String?,
    val gravatar_id: String?,
    val hireable: Any?,
    val html_url: String?,
    val id: String?,
    val location: String?,
    val login: String?,
    val name: String?,
    val node_id: String?,
    val organizations_url: String?,
    val public_gists: String?,
    val public_repos: String?,
    val received_events_url: String?,
    val repos_url: String?,
    val site_admin: Boolean?,
    val starred_url: String?,
    val subscriptions_url: String?,
    val twitter_username: String?,
    val type: String?,
    val updated_at: String?,
    val url: String?
)